# Generated by Django 6.0 on 2026-01-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='categoty',
            new_name='category',
        ),
    ]
